FROM alpine:3.4

RUN apk add --no-cache python3
RUN pip3 install coverage

RUN adduser -S tester

COPY . /infraboxcli
RUN chown -R tester /infraboxcli

WORKDIR /infraboxcli

RUN pip3 install .

USER tester

CMD /infraboxcli/infrabox/infraboxcli/entrypoint.sh
